services:
  coreai-mcu-event:
    build:
      context: .
      target: production
    image: coreai-mcu-event
    container_name: coreai-mcu-event
    depends_on:
      - coreai-mcu-event-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-event-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-event-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-event
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
