services:
  coreai-mcu-event:
    build:
      context: .
      target: production
    image: coreai-mcu-event
    container_name: coreai-mcu-event
    depends_on:
      - coreai-mcu-event-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-event-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://coreai-mcu-event-azurite:10002/devstoreaccount1;
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENT_SUBSCRIPTION_ADDRESS:-coreai-mcu-event-hub}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}

  coreai-mcu-event-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    labels:
      com.docker.compose.pay.role: coreai-mcu-event-azurite

